language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run unit tests
script:
  - tox
  - cd docs; sphinx-build -nWT . _build/html